

include lib.mk

# TODO: Add targets for building static library.

all:
	$(info )


.PHONY: help all clean


clean: 
	$(info )

help:
	$(info *************************************************************************************)
	$(info *             Available make targets                                                *)
	$(info *                                                                                   *)
	$(info *   help:      Display this message                                                 *)
	$(info *   docs:      Build the documentation (requires Doxygen)                           *)
	$(info *   clean:     Clean the documentation's build directory                            *)
	$(info *                                                                                   *)
	$(info *************************************************************************************)